
import React from 'react';
import {
  LayoutDashboard,
  Briefcase,
  CheckSquare,
  FileText,
  Users,
  Bell,
  Search,
  Filter,
  Plus,
  MoreVertical,
  CheckCircle2,
  XCircle,
  Clock,
  ChevronDown,
  ChevronRight,
  AlertCircle,
  AlertTriangle,
  LogOut,
  ArrowRight,
  Upload,
  Download,
  History,
  MessageSquare,
  TrendingUp,
  ShieldCheck,
  CreditCard,
  Activity,
  Zap,
  HardHat,
  Building,
  Building2,
  Calendar,
  DollarSign,
  MapPin,
  Maximize2,
  X,
  PanelLeftOpen,
  Info,
  Lock,
  Eye,
  EyeOff,
  Sun,
  Moon
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Project: Briefcase,
  Briefcase: Briefcase,
  Task: CheckSquare,
  Document: FileText,
  User: Users,
  Notification: Bell,
  Search: Search,
  Filter: Filter,
  Add: Plus,
  More: MoreVertical,
  Approve: CheckCircle2,
  Reject: XCircle,
  Pending: Clock,
  Clock: Clock,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  AlertCircle: AlertCircle,
  Issue: AlertTriangle,
  Logout: LogOut,
  ArrowRight: ArrowRight,
  Upload: Upload,
  Download: Download,
  History: History,
  Comment: MessageSquare,
  Performance: TrendingUp,
  Safety: ShieldCheck,
  Finance: CreditCard,
  Activity: Activity,
  Execution: Zap,
  Labor: HardHat,
  Building: Building,
  Building2: Building2,
  Calendar: Calendar,
  DollarSign: DollarSign,
  MapPin: MapPin,
  FullScreen: Maximize2,
  Close: X,
  Sidebar: PanelLeftOpen,
  Expand: Maximize2,
  Info: Info,
  Lock: Lock,
  Eye: Eye,
  EyeOff: EyeOff,
  Sun: Sun,
  Moon: Moon
};
